[project]
name = "assets"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.asset-leasing]
path = "contracts/asset-leasing.clar"
depends_on = []
